version: '3.3'

services:
  postgres:
    container_name: postgres
    image: kartoza/postgis:11.0-2.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./dhis2/create_dhis_db_and_user.sql:/create_dhis_db_and_user.sql
      - ./ODKAggregate/create_odk_db_and_user.sql:/create_odk_db_and_user.sql
      - ./ODKAggregate/odk.sql:/odk.sql
      - ./dhis2/dhis2.sql:/dhis2.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 12
