version: '3.3'

services:
  mongo:
    container_name: openhim-mongo
    image: mongo:4.2
    volumes:
      - './data/mongo:/data/db'
    healthcheck:
      test: ['CMD-SHELL', 'mongo']
      interval: 5s
      timeout: 5s
      retries: 12

  core:
    container_name: openhim-core
    image: jembi/openhim-core:5
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
      - api_authenticationTypes=["token", "basic"]
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
    depends_on:
      - mongo
    healthcheck:
      test: ['CMD', 'curl', '-k', 'https://localhost:8080/heartbeat']
      interval: 10s
      timeout: 10s
      retries: 12

  console:
    container_name: openhim-console
    image: jembi/openhim-console:1.13
    ports:
        - "9000:80"
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '80']
      interval: 10s
      timeout: 10s
      retries: 12

  # container for executing config import scripts for setting up initial config
  mapper-config-importer:
    container_name: mapper-config-importer
    image: jembi/instantohie-config-importer
    restart: 'no'
    environment:
      OPENHIM_API_HOSTNAME: 'openhim-core'
      OPENHIM_API_PORT: 8080
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'openhim-password'
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - type: bind
        source: ./importer/volume
        target: /importer
    # This command will only attempt to import the OpenHIM config when the heartbeat responds with a 2xx
    command: sh -c "wait-on -t 60000 https-get://core:8080/heartbeat && node openhimConfig.js"
    depends_on:
      - core

  mapper:
    container_name: mapper
    image: jembi/openhim-mediator-mapping:v0.1.0
    restart: on-failure
    environment:
      - OPENHIM_URL=https://core:8080
      - OPENHIM_USERNAME=root@openhim.org
      - OPENHIM_PASSWORD=trace101
    ports:
      - "3003:3003"
    volumes:
      - "./mapper-endpoints:/app/endpoints"
    depends_on:
      - core
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '3003']
      interval: 10s
      timeout: 10s
      retries: 12
