version: '3.3'

volumes:
  dhis-volume:

services:
  postgres:
    container_name: dhis-postgres
    image: kartoza/postgis:11.0-2.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=dhis
      - POSTGRES_PASSWORD=dhis
      - POSTGRES_USER=dhis
    ports:
      - '5432:5432'
    volumes:
      - dhis-volume:/var/lib/postgresql/data
      - ./ODKAggregate/create_db_and_user.sql:/create_db_and_user.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 12
