# adapted from https://github.com/pgracio/dhis2-docker
version: '3.3'

services:
  dhis:
    container_name: dhis-web
    image: researchtriangle/dhis2-web:2.33.2-tomcat7-jre8-latest@sha256:4690492bedef875ccb0d7b181eeb5caf9ed8d062c33ea7087aac980b9c92913f
    environment:
      JAVA_OPTS: '-Xmx1024m -Xms4000m'
      DHIS2_HOME: '/opt/dhis2/config'
      POSTGRES_DB: dhis
    ports:
      - '8081:8080'
    volumes:
      - ./dhis2/wait-for-it.sh:/wait-for-it.sh
      - ./dhis2/dhis.conf:/opt/dhis2/config/dhis.conf
      - ./dhis2/server.xml:/usr/local/tomcat/conf/server.xml
    entrypoint: ./wait-for-it.sh -t 0 postgres:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 10s
      timeout: 10s
      retries: 12
